import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { Activity, ArrowRight, Bot, CarFront, CheckCircle2, ChevronRight, CircleAlert, Gauge, Layers3, MapPinned, Play, Route, ShieldCheck, Sparkles, TrafficCone, Trophy, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { api, Evidence, Graph, ReplayFrame, ScenarioSummary, SolveResult, postJson } from "@/api";

type Page = "home" | "simulation";

function App() {
  const [page, setPage] = useState<Page>("home");
  const [scenarios, setScenarios] = useState<ScenarioSummary[]>([]);
  const [scenarioId, setScenarioId] = useState("S3_BASE");
  const [graph, setGraph] = useState<Graph | null>(null);
  const [closed, setClosed] = useState<string[]>([]);
  const [method, setMethod] = useState("qpso");
  const [solve, setSolve] = useState<SolveResult | null>(null);
  const [previousSolve, setPreviousSolve] = useState<SolveResult | null>(null);
  const [replay, setReplay] = useState<ReplayFrame[]>([]);
  const [frame, setFrame] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [activeTab, setActiveTab] = useState("control");
  const [evidence, setEvidence] = useState<Evidence | null>(null);

  useEffect(() => {
    Promise.all([api<{ scenarios: ScenarioSummary[] }>("/api/scenarios"), api<Graph>(`/api/scenarios/${scenarioId}`)])
      .then(([catalog, nextGraph]) => { setScenarios(catalog.scenarios); setGraph(nextGraph); })
      .catch((err: Error) => setError(err.message));
    api<Evidence>("/api/evidence").then(setEvidence).catch(() => setEvidence({ available: false, reason: "Evidence endpoint unavailable" }));
  }, []);

  useEffect(() => {
    if (page !== "simulation") return;
    api<Graph>(`/api/scenarios/${scenarioId}?closed=${encodeURIComponent(closed.join(","))}`)
      .then(setGraph).catch((err: Error) => setError(err.message));
  }, [scenarioId, closed, page]);

  useEffect(() => {
    if (!replay.length || !isPlaying) return;
    const timer = window.setInterval(() => setFrame((value) => {
      if (value >= replay.length - 1) {
        setIsPlaying(false);
        return value;
      }
      return value + 1;
    }), 120);
    return () => window.clearInterval(timer);
    }, [replay, isPlaying]);

  const activeFrame = replay[frame];
  const activeEdges = useMemo(() => new Set(solve?.evaluation.vehicles.flatMap((vehicle) => vehicle.edge_ids) || []), [solve]);

  async function runSolve() {
    setBusy("solve"); setError("");
    try {
      const result = await postJson<SolveResult>("/api/solve", { scenario_id: scenarioId, method, particles: 12, evaluations: 40, seed: 7, closed_edge_ids: closed });
      setPreviousSolve(solve);
      setSolve(result);
    } catch (err) { setError((err as Error).message); } finally { setBusy(""); }
  }

  async function runReplay() {
    setBusy("replay"); setError("");
    try { const result = await postJson<{ frames: ReplayFrame[] }>("/api/sumo/replay", { scenario_id: scenarioId, plan: solve?.plan || null, closed_edge_ids: closed }); setReplay(result.frames || []); setFrame(0); setIsPlaying(true); }
    catch (err) { setError((err as Error).message); } finally { setBusy(""); }
  }

  function toggleClosure(edgeId: string) { setClosed((items) => items.includes(edgeId) ? items.filter((id) => id !== edgeId) : [...items, edgeId]); }
  function toggleReplay() { if (!replay.length) { void runReplay(); return; } setIsPlaying((value) => !value); }

  if (page === "home") return <Home onStart={() => setPage("simulation")} />;
  return <div className="app-shell">
    <header className="topbar">
      <button className="brand-button" onClick={() => setPage("home")}><span className="brand-mark">✦</span><span>QUANTA</span><Badge variant="outline">SIH26137</Badge></button>
      <nav className="nav-tabs"><button className={activeTab === "control" ? "nav-active" : ""} onClick={() => setActiveTab("control")}>Live Control Room</button><button className={activeTab === "forecast" ? "nav-active" : ""} onClick={() => setActiveTab("forecast")}>Forecast</button><button className={activeTab === "replanning" ? "nav-active" : ""} onClick={() => setActiveTab("replanning")}>Replanning</button><button className={activeTab === "evidence" ? "nav-active" : ""} onClick={() => setActiveTab("evidence")}>Evidence</button></nav>
      <div className="top-status"><span className="live-dot" /> SYSTEM ONLINE <span className="muted">· SUMO READY</span></div>
    </header>
    {error && <div className="error-bar"><CircleAlert size={15} /> {error}<button onClick={() => setError("")}><X size={15} /></button></div>}
    {activeTab === "control" ? <main className="control-layout">
      <section className="control-main">
        <div className="eyebrow"><Activity size={14} /> LIVE DECISION SYSTEM <span>•</span><span className="muted">{scenarioId}</span></div>
        <div className="headline-row"><div><h1>See the decision.<br /><em>Trust the route.</em></h1><p className="lede">Quanta turns traffic disruption into a validated delivery plan in seconds.</p></div><div className="step-rail"><Step label="Observe" active /><Step label="Predict" /><Step label="Replan" /><Step label="Prove" /></div></div>
        <Card className="map-card">
          <CardHeader><div><CardTitle><MapPinned size={17} /> City operations map</CardTitle><CardDescription>Directed roads, delivery fleet, and the route selected by the optimizer.</CardDescription></div><Badge variant={closed.length ? "warning" : "success"}>{closed.length ? `${closed.length} ROAD CLOSURE` : "NETWORK CLEAR"}</Badge></CardHeader>
          <CardContent><NetworkMap graph={graph} routeEdges={activeEdges} closed={closed} movers={activeFrame?.vehicles || []} /><div className="replay-bar"><span className="replay-time">{activeFrame ? `t = ${activeFrame.t.toFixed(0)}s` : "No replay loaded"}</span><input aria-label="SUMO replay timeline" type="range" min="0" max={Math.max(0, replay.length - 1)} value={frame} onChange={(event) => { setIsPlaying(false); setFrame(Number(event.target.value)); }} disabled={!replay.length} /><span className="replay-count">{replay.length ? `${frame + 1} / ${replay.length}` : "—"}</span></div></CardContent>
        </Card>
        <div className="kpi-grid"><Kpi icon={<Gauge />} label="Travel time" value={solve ? `${solve.evaluation.time_s.toFixed(0)} s` : "—"} /><Kpi icon={<Route />} label="Distance" value={solve ? `${(solve.evaluation.distance_m / 1000).toFixed(2)} km` : "—"} /><Kpi icon={<CarFront />} label="Completed delivery" value={solve ? `${solve.evaluation.vehicles.reduce((sum, v) => sum + v.order.length, 0)} / ${graph?.requests.length || 5}` : "—"} accent={solve?.evaluation.all_served ? "good" : ""} /><Kpi icon={<Activity />} label="Replanning latency" value={solve ? `${solve.elapsed_s.toFixed(2)} s` : "—"} /></div>
      </section>
      <aside className="control-sidebar">
        <Card className="control-card"><CardHeader><CardTitle>Run a scenario</CardTitle><CardDescription>Start with a disruption so the system has something meaningful to explain.</CardDescription></CardHeader><CardContent className="control-fields"><Field label="Scenario"><select value={scenarioId} onChange={(e) => { setScenarioId(e.target.value); setSolve(null); setPreviousSolve(null); }}><option value="S3_BASE">Five-job city fixture</option>{scenarios.filter((s) => s.id !== "S3_BASE" && s.available).slice(0, 5).map((s) => <option key={s.id} value={s.id}>{s.label}</option>)}</select></Field><Field label="Optimizer"><select value={method} onChange={(e) => setMethod(e.target.value)}><option value="qpso">QPSO · quantum-inspired</option><option value="pso">PSO · classical comparator</option><option value="alns">ALNS · adaptive heuristic</option><option value="constructive">Constructive baseline</option></select></Field><Field label="Incident"><select value={closed[0] || ""} onChange={(e) => setClosed(e.target.value ? [e.target.value] : [])}><option value="">No active incident</option>{graph?.edges.map((edge) => <option key={edge.id} value={edge.id}>{edge.id} · {edge.from} → {edge.to}</option>)}</select></Field><div className="button-stack"><Button size="lg" onClick={runSolve} disabled={!!busy}><Sparkles size={16} /> {busy === "solve" ? "Solving…" : "Solve & validate"}</Button><Button size="lg" variant="outline" onClick={toggleReplay} disabled={busy === "replay"}><Play size={16} /> {busy === "replay" ? "Loading SUMO…" : replay.length ? (isPlaying ? "Pause SUMO replay" : "Resume SUMO replay") : "Load SUMO replay"}</Button></div></CardContent></Card>
        <Card className="why-card"><CardHeader><CardTitle><Bot size={17} /> Why did it choose this?</CardTitle></CardHeader><CardContent>{solve ? <div className="decision-list"><Decision icon={<TrafficCone />} title={closed.length ? "Closure-aware" : "Traffic-aware"} body={closed.length ? "The blocked road was removed from legal route search." : "The solver used directed road time and service windows."} /><Decision icon={<ShieldCheck />} title="Validator-first" body={solve.evaluation.feasible ? "Every vehicle, customer, time window, and depot return passed." : "The independent validator found a constraint issue."} /><Decision icon={<Activity />} title="Search trace" body={`${solve.method} evaluated ${solve.evaluations || "multiple"} candidate plans.`} /></div> : <div className="empty-explain"><Bot size={30} /><p>Run a scenario to see the reasoning chain here.</p></div>}</CardContent></Card>
      </aside>
      <section className="bottom-grid"><Card><CardHeader><CardTitle>Route result</CardTitle><CardDescription>The exact customer order and road path returned by the backend.</CardDescription></CardHeader><CardContent><RouteTable result={solve} /></CardContent></Card><Card><CardHeader><CardTitle>Convergence</CardTitle><CardDescription>Lower objective is better. This is the optimizer’s actual evaluation trace.</CardDescription></CardHeader><CardContent><Trace values={solve?.trace?.best || []} /></CardContent></Card><Card className="timeline-card"><CardHeader><CardTitle>What happened</CardTitle><CardDescription>A short audit trail for the current run.</CardDescription></CardHeader><CardContent><Timeline solve={solve} replay={replay} /></CardContent></Card></section>
    </main> : activeTab === "forecast" ? <ForecastTab evidence={evidence} graph={graph} /> : activeTab === "replanning" ? <ReplanningTab current={solve} previous={previousSolve} /> : <EvidenceTab evidence={evidence} />}
  </div>;
}

function Home({ onStart }: { onStart: () => void }) { return <div className="home-shell"><header className="home-nav"><button className="brand-button"><span className="brand-mark">✦</span><span>QUANTA</span></button><Button variant="outline" size="sm" onClick={onStart}>Open control room <ArrowRight size={14} /></Button></header><main className="home-main"><div className="hero-copy"><Badge variant="outline">SMART ROUTING FOR DYNAMIC CITIES</Badge><h1>When the city changes,<br /><em>the route adapts.</em></h1><p>Quanta is an adaptive dispatch system for delivery fleets. It watches a directed road network, forecasts near-term traffic, and searches for a route that is legal, fast, and ready to execute.</p><div className="hero-actions"><Button size="lg" onClick={onStart}>Launch live simulation <ArrowRight size={17} /></Button><a href="#method">See the method <ChevronRight size={15} /></a></div><div className="hero-proof"><span><CheckCircle2 size={15} /> Independent validation</span><span><CheckCircle2 size={15} /> SUMO execution</span><span><CheckCircle2 size={15} /> QPSO + baselines</span></div></div><div className="hero-visual"><div className="orbital orbital-one" /><div className="orbital orbital-two" /><div className="city-core"><Layers3 size={42} /><span>LIVE<br />NETWORK</span></div><div className="hero-node node-a" /><div className="hero-node node-b" /><div className="hero-node node-c" /><div className="hero-line line-a" /><div className="hero-line line-b" /><div className="hero-line line-c" /><div className="hero-float float-one"><span className="live-dot" /> FORECAST v1</div><div className="hero-float float-two">QPSO <strong>READY</strong></div></div></main><section id="method" className="home-method"><div><span className="eyebrow">THE DECISION LOOP</span><h2>From signal to safe action.</h2></div><div className="method-grid"><Method number="01" icon={<Activity />} title="Observe" text="Traffic, closures, fleet position, and delivery windows enter one causal state." /><Method number="02" icon={<Bot />} title="Predict" text="The graph forecaster estimates speed by road and horizon with measurable uncertainty." /><Method number="03" icon={<Sparkles />} title="Optimize" text="QPSO searches a route plan, while an independent validator protects feasibility." /><Method number="04" icon={<ShieldCheck />} title="Prove" text="SUMO executes the plan so the result can be replayed and inspected." /></div></section></div> }

function EvidenceTab({ evidence }: { evidence: Evidence | null }) { const validation = (evidence?.uncertainty?.validation?.actual_coverage ?? 0) * 100; const test = (evidence?.uncertainty?.test?.actual_coverage ?? 0) * 100; const modelMae = evidence?.model_mae ?? 0; const baselineMae = evidence?.temporal_baseline_mae ?? 0; return <main className="evidence-page"><div className="eyebrow"><Trophy size={14} /> RESEARCH EVIDENCE</div><h1>What the current system has measured.</h1><p className="lede">The live control room is backed by real SUMO episodes and saved Step 13–14 artifacts. Metrics stay visible even when a model is not yet the winner.</p>{!evidence?.available && <div className="evidence-note"><CircleAlert size={15} /> Saved forecaster artifacts are unavailable to this API process. Build or mount `artifacts/step13_forecaster_v1` to display measured values.</div>}<div className="evidence-grid"><Card><CardHeader><CardTitle>Forecast uncertainty</CardTitle><CardDescription>Residual intervals calibrated on validation data.</CardDescription></CardHeader><CardContent><MetricBar label="Validation coverage" value={validation} target={80} /><MetricBar label="Held-out test coverage" value={test} target={80} warning /><div className="evidence-note"><CircleAlert size={15} /> Test coverage is below nominal; the model remains experimental.</div></CardContent></Card><Card><CardHeader><CardTitle>Forecast comparison</CardTitle><CardDescription>Held-out speed-ratio aggregate.</CardDescription></CardHeader><CardContent><div className="compare-row"><span>GNN–Transformer</span><strong>{modelMae ? `${modelMae.toFixed(4)} MAE` : "Unavailable"}</strong></div><div className="compare-row"><span>Temporal-only baseline</span><strong className="good-text">{baselineMae ? `${baselineMae.toFixed(4)} MAE` : "Unavailable"}</strong></div><Separator /><p className="small-copy">This is an honest comparison: the current neural model has not yet beaten the baseline.</p></CardContent></Card><Card className="evidence-wide"><CardHeader><CardTitle>Architecture status</CardTitle><CardDescription>What runs now and what is being integrated next.</CardDescription></CardHeader><CardContent><div className="status-grid"><StatusLine label="Directed graph + constraints" state="Live" /><StatusLine label="QPSO + PSO + ALNS references" state="Live" /><StatusLine label="SUMO replay" state="Live" /><StatusLine label="GNN–Transformer training" state="Measured" /><StatusLine label="Forecast-aware route cost" state="Measured" /><StatusLine label="Neural forecast in live loop" state="Next" /></div></CardContent></Card></div></main> }

function ForecastTab({ evidence, graph }: { evidence: Evidence | null; graph: Graph | null }) {
  const horizons = [["5 min", "near-term", "Fast reaction window"], ["10 min", "decision", "Primary replanning window"], ["15 min", "extended", "Longer look-ahead"]];
  const coverage = evidence?.uncertainty?.test?.actual_coverage;
  return <main className="evidence-page forecast-page"><div className="eyebrow"><Gauge size={14} /> FORECAST LAYER</div><h1>Traffic before it becomes a delay.</h1><p className="lede">The forecaster is evaluated by road and horizon. This view keeps the three decision horizons visible and labels what is already measured versus what is still being connected to live serving.</p><div className="horizon-grid">{horizons.map(([label, kind, detail]) => <Card className="horizon-card" key={label}><span className="horizon-label">{label}</span><Badge variant="outline">{kind}</Badge><strong>{detail}</strong><small>Road-level speed ratio target</small></Card>)}</div><div className="evidence-grid"><Card><CardHeader><CardTitle>Road forecast preview</CardTitle><CardDescription>{graph ? `${graph.edges.length} legal directed roads in ${graph.scenario_id}` : "Loading graph…"}</CardDescription></CardHeader><CardContent><div className="road-forecast-list">{(graph?.edges || []).slice(0, 7).map((edge) => <div className="road-forecast" key={edge.id}><div><span>{edge.id}</span><small>{edge.from} → {edge.to}</small></div><Progress value={Math.min(100, Math.max(12, edge.speed_mps * 4))} /><em>{edge.speed_mps.toFixed(1)} m/s free flow</em></div>)}</div><p className="small-copy">This is the live network profile used by the planner. Neural road predictions are measured offline in the evidence artifact and are not presented here as fake live values.</p></CardContent></Card><Card><CardHeader><CardTitle>Uncertainty contract</CardTitle><CardDescription>Versioned forecast metadata for planner integration.</CardDescription></CardHeader><CardContent><div className="compare-row"><span>Forecast version</span><strong>forecaster_v1</strong></div><div className="compare-row"><span>Issue time</span><strong>Per forecast request</strong></div><div className="compare-row"><span>Held-out coverage</span><strong className={coverage && coverage >= 0.8 ? "good-text" : "warning-text"}>{coverage == null ? "Unavailable" : `${(coverage * 100).toFixed(1)}%`}</strong></div><Separator /><p className="small-copy">Known closures remain hard constraints. Beyond the served horizon, the planner uses the declared current/time-of-day extension.</p></CardContent></Card></div></main>
}

function ReplanningTab({ current, previous }: { current: SolveResult | null; previous: SolveResult | null }) {
  const planEntries = (plan: Record<string, string[]> | undefined) => Object.entries(plan || {});
  return <main className="evidence-page replanning-page"><div className="eyebrow"><Sparkles size={14} /> REPLANNING TRACE</div><h1>See what changed, and why.</h1><p className="lede">Run the same scenario again after changing an incident to compare the previous plan with the current validated plan.</p><div className="plan-compare"><Card className="plan-box"><CardHeader><CardTitle>Before</CardTitle><CardDescription>{previous ? "Previous solve in this session" : "No previous solve captured"}</CardDescription></CardHeader><CardContent>{previous ? planEntries(previous.plan).map(([vehicle, stops]) => <div className="plan-line" key={vehicle}><strong>{vehicle}</strong><span>{stops.join(" → ") || "No stops"}</span></div>) : <div className="empty-table"><Route size={22} /><span>Run solve twice to create a before/after comparison.</span></div>}</CardContent></Card><Card className="plan-box"><CardHeader><CardTitle>After</CardTitle><CardDescription>{current ? `${current.status} · ${current.evaluation.time_s.toFixed(0)}s` : "Current plan appears here"}</CardDescription></CardHeader><CardContent>{current ? planEntries(current.plan).map(([vehicle, stops]) => <div className="plan-line" key={vehicle}><strong>{vehicle}</strong><span>{stops.join(" → ") || "No stops"}</span></div>) : <div className="empty-table"><Sparkles size={22} /><span>Run a scenario from Live Control Room.</span></div>}</CardContent></Card></div><div className="evidence-grid"><Card><CardHeader><CardTitle>Change driver</CardTitle><CardDescription>The event that can force a new route.</CardDescription></CardHeader><CardContent><div className="route-change"><CircleAlert size={20} /><div><strong>{current?.closed_edge_ids.length ? current.closed_edge_ids.join(", ") : "No closure selected"}</strong><p>{current?.closed_edge_ids.length ? "Closed roads were removed from legal search." : "Change an incident to create a controlled comparison."}</p></div></div></CardContent></Card><Card><CardHeader><CardTitle>QPSO convergence</CardTitle><CardDescription>Search effort and validator outcome.</CardDescription></CardHeader><CardContent><div className="compare-row"><span>Evaluations</span><strong>{current?.evaluations ?? "—"}</strong></div><div className="compare-row"><span>Best objective</span><strong>{current?.trace?.best?.at(-1)?.toFixed(1) ?? "—"}</strong></div><div className="compare-row"><span>Validator</span><strong className={current?.evaluation.feasible ? "good-text" : "warning-text"}>{current ? (current.evaluation.feasible ? "PASS" : "REPAIR") : "—"}</strong></div></CardContent></Card></div></main>
}

function NetworkMap({ graph, routeEdges, closed, movers }: { graph: Graph | null; routeEdges: Set<string>; closed: string[]; movers: ReplayFrame["vehicles"] }) { if (!graph) return <div className="map-loading">Loading network…</div>; const xs = graph.nodes.map((n) => n.x), ys = graph.nodes.map((n) => n.y); const minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys); const point = (n: { x: number; y: number }) => ({ x: 40 + ((n.x - minX) / Math.max(1, maxX - minX)) * 720, y: 360 - ((n.y - minY) / Math.max(1, maxY - minY)) * 300 }); const nodes = Object.fromEntries(graph.nodes.map((n) => [n.id, n])); return <div className="map-wrap"><svg viewBox="0 0 800 400" role="img" aria-label="Directed city road network"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="coloredBlur" /><feMerge><feMergeNode in="coloredBlur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>{graph.edges.map((edge) => { const a = point(nodes[edge.from]), b = point(nodes[edge.to]); const isRoute = routeEdges.has(edge.id); const isClosed = closed.includes(edge.id) || !edge.open; return <line key={edge.id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={`map-edge ${isRoute ? "map-route" : ""} ${isClosed ? "map-closed" : ""}`} markerEnd="url(#arrow)" />; })}{graph.nodes.map((node) => { const p = point(node); return <g key={node.id}><circle cx={p.x} cy={p.y} r={node.kind.includes("depot") ? 10 : 6} className={node.kind.includes("depot") ? "map-depot" : "map-node"} /><text x={p.x + 9} y={p.y - 9} className="map-label">{node.id}</text></g>; })}{graph.requests.map((job) => { const p = point(nodes[job.node]); return <g key={job.id}><circle cx={p.x} cy={p.y} r="3" className="map-job" /><text x={p.x + 9} y={p.y + 15} className="map-job-label">{job.id}</text></g>; })}{movers.map((mover) => { const p = point({ x: mover.x, y: mover.y }); return <circle key={mover.id} cx={p.x} cy={p.y} r={mover.kind === "delivery" ? 8 : 4} className={mover.kind === "delivery" ? "map-mover delivery" : "map-mover traffic"} />; })}</svg><div className="map-legend"><span><i className="legend-line route" />Selected route</span><span><i className="legend-line closed" />Closure</span><span><i className="legend-dot car" />SUMO vehicle</span><span><i className="legend-dot job" />Delivery</span></div></div> }

function Step({ label, active }: { label: string; active?: boolean }) { return <div className={`step ${active ? "step-active" : ""}`}><span className="step-dot" />{label}</div> }
function Kpi({ icon, label, value, accent = "" }: { icon: ReactNode; label: string; value: string; accent?: string }) { return <Card className="kpi"><CardContent><span className="kpi-icon">{icon}</span><div><span className="kpi-label">{label}</span><strong className={accent}>{value}</strong></div></CardContent></Card> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label> }
function Decision({ icon, title, body }: { icon: ReactNode; title: string; body: string }) { return <div className="decision"><span className="decision-icon">{icon}</span><div><strong>{title}</strong><p>{body}</p></div></div> }
function Method({ number, icon, title, text }: { number: string; icon: ReactNode; title: string; text: string }) { return <Card className="method-card"><span className="method-number">{number}</span><span className="method-icon">{icon}</span><CardTitle>{title}</CardTitle><CardDescription>{text}</CardDescription></Card> }
function RouteTable({ result }: { result: SolveResult | null }) { if (!result) return <div className="empty-table"><Route size={24} /><span>Run the solver to see the route explanation.</span></div>; return <div className="route-table">{result.evaluation.vehicles.map((v) => <div className="route-row" key={v.id}><span className={`vehicle-dot ${v.id === "V2" ? "blue" : "lime"}`} /> <strong>{v.id}</strong><span>{v.order.join(" → ") || "No stops"}</span><small>{v.elapsed_s.toFixed(0)}s · {v.edge_ids.length} roads</small></div>)}</div> }
function Timeline({ solve, replay }: { solve: SolveResult | null; replay: ReplayFrame[] }) { const events = solve ? [{ label: "Plan validated", detail: solve.evaluation.feasible ? "All hard constraints pass" : "Validator requested repair" }, { label: "Route selected", detail: `${solve.evaluation.vehicles.length} delivery vehicles assigned` }, { label: "SUMO replay", detail: replay.length ? `${replay.length} frames ready` : "Replay not loaded" }] : [{ label: "Waiting for scenario", detail: "Choose an incident and solve to begin" }]; return <div className="timeline">{events.map((event, index) => <div className="timeline-item" key={event.label}><span className={`timeline-dot ${index === 0 && solve ? "active" : ""}`} /><div><strong>{event.label}</strong><small>{event.detail}</small></div></div>)}</div> }
function Trace({ values }: { values: number[] }) { if (values.length < 2) return <div className="empty-table"><Activity size={24} /><span>Solve a route to reveal the search trace.</span></div>; const min = Math.min(...values), max = Math.max(...values); const points = values.map((v, i) => `${(i / (values.length - 1)) * 100},${92 - ((v - min) / Math.max(1e-6, max - min)) * 72}`).join(" "); return <div className="trace-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2.5" vectorEffect="non-scaling-stroke" /></svg><div className="trace-caption"><span>Best objective</span><strong>{values[values.length - 1].toFixed(1)}</strong></div></div> }
function MetricBar({ label, value, target, warning }: { label: string; value: number; target: number; warning?: boolean }) { return <div className="metric-bar"><div><span>{label}</span><strong className={warning ? "warning-text" : ""}>{value.toFixed(1)}%</strong></div><Progress value={value} /><small>Nominal target {target}%</small></div> }
function StatusLine({ label, state }: { label: string; state: string }) { return <div className="status-line"><span>{label}</span><Badge variant={state === "Live" ? "success" : state === "Measured" ? "warning" : "secondary"}>{state}</Badge></div> }

export default App;
